services:
  stops-getter-v3:
    image: thalvadzhiev/sumc_stops_getter:latest
    build: .
    platform: linux/arm/v6
    command: sh ./docker/entry_script.sh
    restart: unless-stopped
    working_dir: /home/sumc
    dns:
      - 8.8.8.8
      - 4.4.4.4
    volumes:
      - /etc/localtime:/etc/localtime
      - ../:/home/sumc