services:
  stops-getter-v3:
    image: sofia-traffic-stops-getter:latest
    build:
      context: ./
      dockerfile: Dockerfile-ubuntu

    platform: linux/amd64

    working_dir: /home/sumc
    dns:
      - 8.8.8.8
      - 4.4.4.4
    network_mode: bridge
    volumes:
      - /etc/localtime:/etc/localtime
#      - ../:/home/sumc
    secrets:
      - ssh_key_stops_getter
    environment:
      SSH_KEY: /run/secrets/ssh_key_stops_getter


secrets:
  ssh_key_stops_getter:
    file: ./ssh_key