FROM ubuntu:oracular-20240913

RUN apt update && apt install -y git python3 python3-pip libgeos-dev libopenblas-dev openssh-client

ARG path_to_package=/home/sumc/package
ARG path_to_repo=/home/sumc


RUN mkdir -p ${path_to_repo}

RUN git clone https://github.com/thalvadzhi/Sofia-Traffic-Stops-Getter.git ${path_to_repo}


RUN python3 -m pip install -r ${path_to_repo}/requirements.txt --break-system-packages


RUN git config --global user.name raspberry-getter
RUN git config --global user.email devthebear@gmail.com
RUN git config --global --add safe.directory ${path_to_repo}

COPY entry_script.sh ${path_to_repo}
RUN chmod +x ${path_to_repo}/entry_script.sh

RUN mkdir -p ~/.ssh
RUN ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

WORKDIR ${path_to_repo}

CMD ["./entry_script.sh"]
